"""Deterministic HVAC component models."""

from agent_hvac.components.compressor_map import (
    CompressorMapInput,
    CompressorMapResult,
    evaluate_compressor_map,
)
from agent_hvac.components.expansion_valve_map import (
    ExpansionValveMapInput,
    ExpansionValveMapResult,
    evaluate_expansion_valve_map,
)
from agent_hvac.components.heat_exchanger_1d import (
    HeatExchanger1DInput,
    HeatExchanger1DResult,
    HeatExchangerCellResult,
    HeatExchangerMode,
    SpecificHeatCapacity,
    ThermalConductance,
    evaluate_heat_exchanger_1d,
)
from agent_hvac.components.heat_exchanger_rated_point import (
    HeatExchangerBoundaryInput,
    HeatExchangerRatedPointError,
    HeatExchangerRatedPointResult,
    HeatExchangerRatedPointSelection,
    HeatExchangerRatedPointView,
    RatedValueTrace,
    evaluate_heat_exchanger_rated_point,
    select_heat_exchanger_rated_point,
)
from agent_hvac.components.performance_map import (
    EnvelopeVertex,
    FixedCondition,
    MapAxis,
    MapEvaluation,
    MapOutput,
    MapPoint,
    OperatingEnvelope2D,
    PerformanceMapError,
    RegularGridMap,
    evaluate_regular_grid,
    require_envelope_contains,
)
from agent_hvac.components.pipe import (
    DynamicViscosity,
    LinearHeatTransferCoefficient,
    NonnegativeLength,
    Pipe1DInput,
    Pipe1DResult,
    PipeCellResult,
    evaluate_pipe_1d,
)
from agent_hvac.components.product_adapter import (
    adapt_product_operating_envelope,
    adapt_product_performance_map,
)

__all__ = [
    "DynamicViscosity",
    "CompressorMapInput",
    "CompressorMapResult",
    "EnvelopeVertex",
    "ExpansionValveMapInput",
    "ExpansionValveMapResult",
    "FixedCondition",
    "HeatExchanger1DInput",
    "HeatExchanger1DResult",
    "HeatExchangerCellResult",
    "HeatExchangerMode",
    "HeatExchangerBoundaryInput",
    "HeatExchangerRatedPointError",
    "HeatExchangerRatedPointResult",
    "HeatExchangerRatedPointSelection",
    "HeatExchangerRatedPointView",
    "LinearHeatTransferCoefficient",
    "MapAxis",
    "MapEvaluation",
    "MapOutput",
    "MapPoint",
    "NonnegativeLength",
    "OperatingEnvelope2D",
    "Pipe1DInput",
    "Pipe1DResult",
    "PipeCellResult",
    "PerformanceMapError",
    "RegularGridMap",
    "RatedValueTrace",
    "SpecificHeatCapacity",
    "ThermalConductance",
    "adapt_product_operating_envelope",
    "adapt_product_performance_map",
    "evaluate_heat_exchanger_1d",
    "evaluate_heat_exchanger_rated_point",
    "evaluate_compressor_map",
    "evaluate_expansion_valve_map",
    "evaluate_pipe_1d",
    "evaluate_regular_grid",
    "require_envelope_contains",
    "select_heat_exchanger_rated_point",
]
